version: '3'

services:

  postgres:
    image: postgres
    restart: always
    environment:
      - POSTGRES_DB=aucarvideo
      - POSTGRES_PASSWORD=aucarvideo
      - POSTGRES_USER=aucarvideo
    expose:
      - "5432"

  web:
    build: ./aucarvideo
    restart: always
    entrypoint: ./entrypoint.sh
    environment:
      - PRODUCTION=on
    volumes:
      - ./aucarvideo:/usr/src/app
      - static:/usr/src/app/static
    depends_on:
      - postgres

  nginx:
    image: nginx
    restart: on-failure
    ports: 
     - "80:80"
    volumes:
     - static:/usr/share/nginx/html/static
     - ./nginx/conf.d:/etc/nginx/conf.d
    depends_on:
      - web

volumes:
  static: