version: '3'

services:

  postgres:
    image: postgres
    restart: always
    environment:
      - POSTGRES_DB=aucarvideo
      - POSTGRES_PASSWORD=aucarvideo
      - POSTGRES_USER=aucarvideo
    expose:
      - "5432"

  web:
    build: ./aucarvideo
    restart: always
    entrypoint: ./entrypoint.sh
    environment:
      - PRODUCTION=on
    volumes:
      - ./aucarvideo:/usr/src/app
      # The static folder is being shared 
      # between 'web' and 'nginx' services,
      # so nginx can serve the static files.
      - static:/usr/src/app/static
      # The media folder is being shared 
      # between 'web' and 'cron' services
      - media:/usr/src/app/media
    depends_on:
      - postgres

  nginx:
    image: nginx
    restart: on-failure
    ports: 
      - "80:80"
    volumes:
      # The static folder is being shared 
      # between 'web' and 'nginx' services,
      # so nginx can serve the static files.
      - static:/usr/share/nginx/html/static
      - ./nginx/conf.d:/etc/nginx/conf.d
    depends_on:
      - web

  cron:
    build: ./cron
    # restart: always
    entrypoint: ./entrypoint.sh
    environment:
      - CRON_MINUTE=*/1 * * * * root echo "Hello minute"
      # - CRON_MINUTE=*/1 * * * * root /usr/src/app/script.sh
      # - CRON_HOUR=0 * * * * root echo "Hello hour"
    volumes:
      - ./cron:/usr/src/app/
      # The media folder is being shared 
      # between 'web' and 'cron' services
      - media:/usr/src/app/media
    # To keep container running
    # stdin_open: true
    # tty: true

volumes:
  static:
  media: