version: '3'

services:

  postgres:
    image: postgres
    env_file: environment
    restart: always
    expose:
      - "5432"

  web:
    build: ./aucarvideo
    env_file: environment
    restart: always
    volumes:
      - ./aucarvideo:/usr/src/app
      # - ./resolv.conf:/etc/resolv.conf
      - static:/usr/src/app/static
    entrypoint: ./entrypoint.sh
    depends_on:
      - postgres
    # dns:
    #   - 190.157.8.33
    #   - 190.157.8.1
    #   - 8.8.8.8
      # - nginx
    # dns: 8.8.8.8
    # dns_opt:
    #   - use-vc
    #   - no-tld-query

        # volumes:
        #     - ./resolv.conf:/etc/resolv.conf


  nginx:
    image: nginx
    restart: on-failure
    ports: 
     - "80:80"
    volumes:
     - static:/usr/share/nginx/html/static
     - ./nginx/conf.d:/etc/nginx/conf.d
    depends_on:
      - web

volumes:
  static: